# Generated by Django 2.2.4 on 2019-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190618_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
