# Generated by Django 2.2.4 on 2019-12-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191203_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='dateandtime',
        ),
    ]
